// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-N4HCPW-QSwTY6gAb-Oa_-VpcJ0fe_zc',
    appId: '1:985158664091:web:e57c3ee75b900762b42b3e',
    messagingSenderId: '985158664091',
    projectId: 'spotfinder-a7e90',
    authDomain: 'spotfinder-a7e90.firebaseapp.com',
    storageBucket: 'spotfinder-a7e90.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEO7jaqwsycLcyqPHnT_o4yGep7UydS9I',
    appId: '1:985158664091:android:2128b539139b82dab42b3e',
    messagingSenderId: '985158664091',
    projectId: 'spotfinder-a7e90',
    storageBucket: 'spotfinder-a7e90.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBo0-TGyi6NIQ5tRTvaRGFJD0Vo4v4ip7g',
    appId: '1:985158664091:ios:02ea0b859d77df38b42b3e',
    messagingSenderId: '985158664091',
    projectId: 'spotfinder-a7e90',
    storageBucket: 'spotfinder-a7e90.appspot.com',
    iosBundleId: 'com.example.spotFinder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBo0-TGyi6NIQ5tRTvaRGFJD0Vo4v4ip7g',
    appId: '1:985158664091:ios:f5771c07c91780b5b42b3e',
    messagingSenderId: '985158664091',
    projectId: 'spotfinder-a7e90',
    storageBucket: 'spotfinder-a7e90.appspot.com',
    iosBundleId: 'com.example.spotFinder.RunnerTests',
  );
}
